[env:treklink-v2]
extends = esp32s3_base
board = esp32-s3-devkitc-1
board_build.partitions = default_8MB.csv
board_check = true

lib_deps =
  ${esp32s3_base.lib_deps}
  ${radiolib_base.lib_deps}
  ${environmental_base.lib_deps}

build_flags =
  ${esp32s3_base.build_flags}
  -D TREKLINK_VARIANT
  -D TREKLINK_V2
  -D HAS_SCREEN=1
  -I variants/esp32s3/treklink_v2_0
