[env:treklink]
extends = esp32_base
board = treklink-esp32
build_flags =
  ${esp32_base.build_flags} -D TREKLINK_VARIANT
  -I variants/esp32/treklink_v1_0
  -D HAS_SCREEN=1                      # Enable screen modules (OLED SSD1306)
  -D USE_CANNED_MESSAGE_MODULE=1       # Enable canned message functionality
  -D MESHTASTIC_EXCLUDE_POWER_TELEMETRY=1       # No power monitoring ICs (INA219/226/260)
  -D MESHTASTIC_EXCLUDE_MQTT=1                   # No MQTT
lib_deps =
  ${esp32_base.lib_deps}
  ${networking_base.lib_deps}
  ${radiolib_base.lib_deps}
  ${environmental_base.lib_deps}
