[env:treklink]
extends = esp32_base
board = treklink-esp32
build_flags =
  ${esp32_base.build_flags} -D TREKLINK
  -I variants/esp32/treklink
lib_deps =
  ${esp32_base.lib_deps}
  ${networking_base.lib_deps}
  ${radiolib_base.lib_deps}
  ${environmental_base.lib_deps}
